
[package]
authors = ["xingwangzhe"]
edition = "2021"
name = "force-rs"
version = "0.1.6"
description = "Fast force-directed 3D graph layout with Barnes-Hut octree and Rayon parallelism"
license = "MIT"

[lib]
crate-type = ["cdylib"]

[dependencies]
napi = "3.0.0"
napi-derive = "3.0.0"
rayon = "1.12.0"

[build-dependencies]
napi-build = "2"

[profile.release]
lto = true
strip = "symbols"
codegen-units = 1
