// prettier-ignore
/* eslint-disable */
// @ts-nocheck
/* auto-generated by NAPI-RS — simplified: removed unused optional-dependency fallbacks (single-package merged build) */

const { readFileSync } = require('fs')
let nativeBinding = null
const loadErrors = []

const isMusl = () => {
  let musl = false
  if (process.platform === 'linux') {
    musl = isMuslFromFilesystem()
    if (musl === null) {
      musl = isMuslFromReport()
    }
    if (musl === null) {
      musl = isMuslFromChildProcess()
    }
  }
  return musl
}

const isFileMusl = (f) => f.includes('libc.musl-') || f.includes('ld-musl-')

const isMuslFromFilesystem = () => {
  try {
    return readFileSync('/usr/bin/ldd', 'utf-8').includes('musl')
  } catch {
    return null
  }
}

const isMuslFromReport = () => {
  let report = null
  if (process.report && typeof process.report.getReport === 'function') {
    process.report.excludeNetwork = true
    report = process.report.getReport()
  }
  if (!report) {
    return null
  }
  if (report.header && report.header.glibcVersionRuntime) {
    return false
  }
  if (Array.isArray(report.sharedObjects)) {
    if (report.sharedObjects.some(isFileMusl)) {
      return true
    }
  }
  return false
}

const isMuslFromChildProcess = () => {
  try {
    return require('child_process').execSync('ldd --version', { encoding: 'utf8' }).includes('musl')
  } catch (e) {
    return false
  }
}

function requireNative() {
  if (process.env.NAPI_RS_NATIVE_LIBRARY_PATH) {
    try {
      return require(process.env.NAPI_RS_NATIVE_LIBRARY_PATH)
    } catch (err) {
      loadErrors.push(err)
    }
  }

  const platform = process.platform
  const arch = process.arch

  // All platform .node binaries are bundled in this package — load directly
  if (platform === 'android') {
    if (arch === 'arm64') {
      try { return require('./force-rs.android-arm64.node') } catch (e) { loadErrors.push(e) }
    } else if (arch === 'arm') {
      try { return require('./force-rs.android-arm-eabi.node') } catch (e) { loadErrors.push(e) }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on Android: ${arch}`))
    }
  } else if (platform === 'win32') {
    if (arch === 'x64') {
      try { return require('./force-rs.win32-x64-msvc.node') } catch (e) { loadErrors.push(e) }
      try { return require('./force-rs.win32-x64-gnu.node') } catch (e) { loadErrors.push(e) }
    } else if (arch === 'ia32') {
      try { return require('./force-rs.win32-ia32-msvc.node') } catch (e) { loadErrors.push(e) }
    } else if (arch === 'arm64') {
      try { return require('./force-rs.win32-arm64-msvc.node') } catch (e) { loadErrors.push(e) }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on Windows: ${arch}`))
    }
  } else if (platform === 'darwin') {
    try { return require('./force-rs.darwin-universal.node') } catch (e) { loadErrors.push(e) }
    if (arch === 'x64') {
      try { return require('./force-rs.darwin-x64.node') } catch (e) { loadErrors.push(e) }
    } else if (arch === 'arm64') {
      try { return require('./force-rs.darwin-arm64.node') } catch (e) { loadErrors.push(e) }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on macOS: ${arch}`))
    }
  } else if (platform === 'freebsd') {
    if (arch === 'x64') {
      try { return require('./force-rs.freebsd-x64.node') } catch (e) { loadErrors.push(e) }
    } else if (arch === 'arm64') {
      try { return require('./force-rs.freebsd-arm64.node') } catch (e) { loadErrors.push(e) }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on FreeBSD: ${arch}`))
    }
  } else if (platform === 'linux') {
    const musl = isMusl()
    if (arch === 'x64') {
      if (musl) {
        try { return require('./force-rs.linux-x64-musl.node') } catch (e) { loadErrors.push(e) }
      } else {
        try { return require('./force-rs.linux-x64-gnu.node') } catch (e) { loadErrors.push(e) }
      }
    } else if (arch === 'arm64') {
      if (musl) {
        try { return require('./force-rs.linux-arm64-musl.node') } catch (e) { loadErrors.push(e) }
      } else {
        try { return require('./force-rs.linux-arm64-gnu.node') } catch (e) { loadErrors.push(e) }
      }
    } else if (arch === 'arm') {
      if (musl) {
        try { return require('./force-rs.linux-arm-musleabihf.node') } catch (e) { loadErrors.push(e) }
      } else {
        try { return require('./force-rs.linux-arm-gnueabihf.node') } catch (e) { loadErrors.push(e) }
      }
    } else if (arch === 'loong64') {
      if (musl) {
        try { return require('./force-rs.linux-loong64-musl.node') } catch (e) { loadErrors.push(e) }
      } else {
        try { return require('./force-rs.linux-loong64-gnu.node') } catch (e) { loadErrors.push(e) }
      }
    } else if (arch === 'riscv64') {
      if (musl) {
        try { return require('./force-rs.linux-riscv64-musl.node') } catch (e) { loadErrors.push(e) }
      } else {
        try { return require('./force-rs.linux-riscv64-gnu.node') } catch (e) { loadErrors.push(e) }
      }
    } else if (arch === 'ppc64') {
      try { return require('./force-rs.linux-ppc64-gnu.node') } catch (e) { loadErrors.push(e) }
    } else if (arch === 's390x') {
      try { return require('./force-rs.linux-s390x-gnu.node') } catch (e) { loadErrors.push(e) }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on Linux: ${arch}`))
    }
  } else if (platform === 'openharmony') {
    if (arch === 'arm64') {
      try { return require('./force-rs.openharmony-arm64.node') } catch (e) { loadErrors.push(e) }
    } else if (arch === 'x64') {
      try { return require('./force-rs.openharmony-x64.node') } catch (e) { loadErrors.push(e) }
    } else if (arch === 'arm') {
      try { return require('./force-rs.openharmony-arm.node') } catch (e) { loadErrors.push(e) }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on OpenHarmony: ${arch}`))
    }
  } else {
    loadErrors.push(new Error(`Unsupported OS: ${platform}, architecture: ${arch}`))
  }
}

nativeBinding = requireNative()

// NAPI_RS_FORCE_WASI is a tri-state flag:
//   unset / any other value → native binding preferred, WASI is only a fallback
//   'true'                   → force WASI fallback even if native loaded
//   'error'                  → force WASI and throw if no WASI binding is found
const forceWasi =
  process.env.NAPI_RS_FORCE_WASI === 'true' || process.env.NAPI_RS_FORCE_WASI === 'error'

if (!nativeBinding || forceWasi) {
  let wasiBinding = null
  let wasiBindingError = null
  try {
    wasiBinding = require('./force-rs.wasi.cjs')
    nativeBinding = wasiBinding
  } catch (err) {
    if (forceWasi) {
      wasiBindingError = err
    }
  }
  if (process.env.NAPI_RS_FORCE_WASI === 'error' && !wasiBinding) {
    const error = new Error('WASI binding not found and NAPI_RS_FORCE_WASI is set to error')
    error.cause = wasiBindingError
    throw error
  }
}

if (!nativeBinding) {
  if (loadErrors.length > 0) {
    const error = new Error(
      `Cannot find native binding for the current platform (${process.platform}-${process.arch}). ` +
        'All platform binaries are bundled in this package. ' +
        'If you see this error, the current platform may not be supported. ' +
        'Please check the package documentation for supported platforms.',
    )
    error.cause = loadErrors.reduce((err, cur) => {
      cur.cause = err
      return cur
    })
    throw error
  }
  throw new Error(`Failed to load native binding`)
}

module.exports = nativeBinding
module.exports.simTick = nativeBinding.simTick
