/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class Simulation {
  tick(state: Float64Array, opts: ForceOptions): Float64Array
}

export declare function createSimulation(links: Uint32Array, n: number): Simulation

export interface ForceOptions {
  repulsion: number
  linkDistance: number
  centerStrength: number
  theta: number
  velocityDecay: number
  alphaDecay: number
  algorithm?: 'fast' | 'linear' | 'legacy'
  distanceMax?: number
}

export declare function simTick(state: Array<number>, links: Array<number>, n: number, opts: ForceOptions): Array<number>
