/* auto-generated by NAPI-RS */
/* eslint-disable */

/**
 * Which binding artifact the generated loader actually loaded: `'native'` for
 * a native addon, otherwise the `platformArchABI` of the WASI flavor. Every
 * flavor napi-rs can build is listed, because `NAPI_RS_NATIVE_LIBRARY_PATH`
 * can point the loader at a WASI artifact this package does not build itself.
 */
export declare const __napiBindingTarget: 'native' | 'wasm32-wasi' | 'wasm32-wasip1'

export declare class Simulation {
  tick(state: Float64Array, opts: ForceOptions): Float64Array
}

export declare function createSimulation(links: Uint32Array, n: number): Simulation

export interface ForceOptions {
  repulsion: number
  linkDistance: number
  centerStrength: number
  theta: number
  velocityDecay: number
  alphaDecay: number
  algorithm?: string
  distanceMax?: number
}

export declare function simTick(state: Array<number>, links: Array<number>, n: number, opts: ForceOptions): Array<number>
